### ISSUE TITLE
No way to contact you

### ISSUE THREAD

**Issue by FroogalTheDragon** [caballero03/php-microservice#1]
Hey there!  This is the guy that you streamed with on D-Live a long time ago, this is McNoodle.  This is a rather unorthodox way to contact you but I can't find your contact info anywhere and I would love to catch up and see how you are, you are one of the only other software devs I know.

Shoot me an email at codecannamw@gmail.com if you have time to catch up!

**Comment by caballero03** [comment]
Email written. Good to hear from you. :-)
